### ISSUE TITLE
Replacement Reader (2000 Gold)

### ISSUE THREAD

**Issue by mikera** [Convex-Dev/bounties#7]
Currently Convex uses Parboiled (https://github.com/sirthias/parboiled) as a Reader. While parboiled does its job well as a fast PEG Parser, it has a few problems:

- It isn't being actively maintained
- It uses a lot of bytecode magic to build parsers with ASM, which causes JVM compatibility and build issues

Objective of this bounty it to replace Parboiled with a dedicated Convex reader. Requirements:

- Must be able to express Reader rules in a customisable way, similar to Parboiled
- Must produce full CVM values (Cells) as parse results
- Must be pure Java
- Must pass all current Reader tests in Convex main repo
- Must support meaningful parse error messages

**Comment by Engelberg** [comment]
Can you post some links to the current convex grammar and parsing code? I'm interested in seeing what the existing code looks like to get a feeling for what would be involved in modifying it. Thanks.

**Comment by mikera** [comment]
It's pretty self-contained in the Reader file: https://github.com/Convex-Dev/convex/blob/master/src/main/java/convex/core/lang/Reader.java

Should be plenty of tests to verify the equivalence of any replacement.

As mentioned in the call, I think ANTLR may be a good choice.

**Comment by mikera** [comment]
https://github.com/antlr/grammars-v4/blob/master/clojure/Clojure.g4

Clojure grammar example!

**Comment by mikera** [comment]
@Engelberg are you interested in taking a crack at this? Would be nice to get it in for the Alpha Release

**Comment by Engelberg** [comment]
I do find the challenge interesting, but I'm deep into a puzzle project right now that is taking all my time. I'm glad to see Bill is making rapid progress on this!

**Comment by mikera** [comment]
OK thanks for letting me know @Engelberg .

@billbsing I think this is potentially a blocker for alpha so I'm going to take a crack at it myself. Let me know if you want to collab!

**Comment by mikera** [comment]
Closing because already completed! ANTLR Reader now ready for use.
